### ISSUE TITLE
Add basic support for including devices basic on the generic device categories. In case specific version is not in the devicetypes file.

### ISSUE THREAD

**Issue by rodtoll** [rodtoll/isy-js#11]
Suggestion from: @robwbartel 

I fully understand I may be naive, but after a cursory reading of http://www.insteon.com/pdf/insteon_devcats_and_product_keys_20081008.pdf it seems to me there could be a default IsyDevice for at least device categories 01 and 02 (dimmable and switched devices respectively) that would eliminate a lot of missed device types for a lot of people. In my network of perhaps 20 devices only two were in the current isydevicelist.js.

**Comment by rodtoll** [comment]
@robwbartel

Latest change https://github.com/rodtoll/isy-js/commit/a39beb21a1afeab6d0eefc0192655d186717d997 now includes the initial version of this.

Note that the device categories didn't turn out to be as clean as one would like. For instance fans appear in category 2 even though they are not a dimmable light. I would expect the fan to appear in a different category and it's light to appear in the dimmable light category. (Both appear as lights).

So I implemented it as using the config file as primary and falling back to the generic code as secondary. As the code improves might be able to eliminate the file completely.

If you get a chance try it against your network see how well it identifies devices and let me know. It completely handles my network obviously but would like to hear how it does against others.

**Comment by robwbartel** [comment]
I agree that was the best you could do. I didn't study it carefully, but the device identification stuff looked kind of haphazard to me so I wasn't expecting anything perfect. What I was hoping was that the Insteon folks would have a REST API or something to a database of their products with generic capabilities each has.

In any event, your changes seem to work great for my network - e.g. it appears to get my 10-year old Icon devices right.

**Comment by rodtoll** [comment]
@robwbartel Thanks for confirming. Glad to hear it is working for you.
