### ISSUE TITLE
Can't control I/O Linc Relays

### ISSUE THREAD

**Issue by PaulWieland** [rodtoll/isy-js#12]
There are two halves to the I/O Linc, the sensor and the relay. It is represented in the ISY's /rest/nodes interface as two separate nodes like this:

``` XML
<node flag="128">
<address>13 34 9B 1</address>
<name>Garage Door-Sensor</name>
<parent type="3">31846</parent>
<type>7.0.54.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>13 34 9B 1</pnode>
<ELK_ID>C11</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="on/off"/>
</node>

<node flag="0">
<address>13 34 9B 2</address>
<name>Garage Door-Relay</name>
<parent type="3">31846</parent>
<type>7.0.54.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>13 34 9B 1</pnode>
<ELK_ID>C12</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="on/off"/>
</node>
```

<del>It seems that the ISY-JS library only reads the sensor, skipping the relay altogether. The sensor and the relay have the same device type so both are setup as a `ISYDoorWindowDevice`.</del>

I just realized that the devicetypes.js file designates which nodes are what based on device type **AND** address. Address 1 is the sensor, makes perfect sense for it to be setup as `ISYDoorWindowDevice`.

However, address 2 for I/O Lincs isn't in the isydevicetypes.json file at all. The question is which device type should it be? Typically relays are opened and closed, not turned on or off, so I don't know if it makes sense to re-use a light or a switch device type for it. Should there be a new one called "Relay"?

**Comment by rodtoll** [comment]
@fahrvergnuugen As you suggest above you can separate the two sub-devices. 

You can treat the relay as a light switch. It uses the same underlying rest commands. You switch it on and off. I checked and the API is the same as for a light. This should enable you to control it. Just don't try to dim it.

For completeness I'll add to my work list better handling of the I/O Lincs. Perhaps a new device type which has both a sensor and a relay OR just create a new relay type and have the sensor be a doorwindowdevice. Open to opinions. 

It would be nice to have a garage door type though. I'll give that some thought -- the library would need to know when to treat an I/O Linc as a relay + sensor and when to treat it as a single garage door object. Essentially some kind of type override. 

The devicetypes.js has been pretty limiting. I'm looking into generic device classes to eliminate the need for the file. (As suggested. :)).

**Comment by PaulWieland** [comment]
Agree on the garage door type, it will make interaction with Siri smoother ("Siri, turn all the lights on" won't accidentally result in the garage door being opened). I had submitted that request to the Homebridge-ISY project before realizing that the relay wasn't setup in the ISY-JS project yet.

Insteon sells a garage door control kit that is nothing more than a reed switch bundled with an I/O Linc, so I'm guessing that 80%+ of the installations are for garage doors. Maybe it makes sense to make a new garage door type and default it for I/O Lincs, but provide a way for the user to override it and split it into separate sensor & switch nodes by device address in case they used an I/O linc for something else.

**Comment by rodtoll** [comment]
The new generic enumeration code should provide a light switch for the IOLinc relays now. 

Going to address garage door in separate issue.

**Comment by rodtoll** [comment]
Changes pushed to npm package.
