### ISSUE TITLE
loadElkNodes fails on initialization - no Elk system installed

### ISSUE THREAD

**Issue by bdstark** [rodtoll/isy-js#14]
I do not have an Elk system installed or enabled on my isy994i. When running isy.initialize, I am getting an error:

``` javascript
var setBaseInfo = function(config, callback) {
    var isy = new ISY.ISY(config.ipAddress, config.username, config.password, isyChangeCallback, false, true);

    isy.initialize(function() {
        callback(isy);
    });
}
```

```
./node_modules/isy-js/isy.js:321
    var nodes = document.childNamed('areas').childNamed('area').childrenNamed('zone');
                                            ^

TypeError: Cannot read property 'childNamed' of undefined
    at ISY.loadElkNodes (./node_modules/isy-js/isy.js:321:45)
    at Request.<anonymous> (./node_modules/isy-js/isy.js:395:30)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.mixin._fireSuccess (./node_modules/restler/lib/restler.js:229:10)
    at ./node_modules/restler/lib/restler.js:161:20
    at IncomingMessage.parsers.auto (./node_modules/restler/lib/restler.js:402:7)
    at Request.mixin._encode (./node_modules/restler/lib/restler.js:198:29)
    at ./node_modules/restler/lib/restler.js:157:16
    at Request.mixin._decode (./node_modules/restler/lib/restler.js:173:7)
```

**Comment by bdstark** [comment]
Tracking it down, it looks like a bug in the isy itself (UD994 v.4.3.26 (2015-10-13). 

http://{ip}/rest/elk/get/topology returns 200, but the body is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<RestResponse succeeded="false">
    <status>404</status>
</RestResponse>
```

**Comment by rodtoll** [comment]
Hey there. In the latest library you should be able to turn off elk support so it won't even make the call. Looking at your source it looks like your reversed the callback and the Elkenabled parameters. Try reversing those and see if it helps.

**Comment by rodtoll** [comment]
Looking at the readme I got them reversed in the getting started section as well. Argh. Sorry for the mistake. 

Look lower in the api docs for the right parameter ordering and descriptions for the constructor. I'll fix the readme getting started section soon.

**Comment by rodtoll** [comment]
@bdstark Fixed the README.md so the parameters are in the right order. Let me know if changing the parameters fixes your issue.

**Comment by bdstark** [comment]
Yes, this gets past the Elk issue. I am now hitting a problem initializing the webSocket unfortunately, but this problem looks to be corrected. If I find anything there, I'll write up another issue in a bit.

Thanks for the fast investigation!
