### ISSUE TITLE
Invalid Date on lastChanged

### ISSUE THREAD

**Issue by tehshane** [rodtoll/isy-js#18]
The value for `lastChanged` is always getting set to "Invalid Date". This appears to happen because the value of `ts` coming from my ISY is in the format "YYYYMMDD HH:MM:SS" which `new Date()` is choking on. 

Might this be unique to how I have my ISY or computer set up, or could it be related to running beta firmware v5.0.2? What format is everyone else's ISY sending `ts` in?

**Comment by rodtoll** [comment]
I just published 0.4.2 to npm which should fix this issue. Turns out I wasn't parsing the date correctly. Also turns out my unit tests were formatting the date differently which would not result in an invalid date. Thanks for pointing this out.

**Comment by tehshane** [comment]
My pleasure! And thanks for this great project. I'm in the midst of refactoring my home automation app to use ISY-JS over the rickety wrapper I'd hobbled together. So much easier to work with. :)

**Comment by rodtoll** [comment]
😀 great to hear it is helping you with your app. If you end up releasing it send me a pointer.
