### ISSUE TITLE
Implementing ISYWindowCoveringDevice to support Somfy Z-Wave Blinds

### ISSUE THREAD

**Issue by cptechie** [rodtoll/isy-js#21]
Would be awesome if we implement ISYWindowCoveringDevice to control blinds, specifically the Somfy ZRTSI in this scenario.

The ZRTSI has 16 "virtual nodes" (or "channels). Each channel is added as two nodes within ISY, one that shows up as a binary switch, and the other that shows up as a motor. The motor has _1 appended to the address where as the switch has _147 appended to the address.

The commands DON and DOFF allows the switch to open (DON) and close (DOFF) the window covering. The same applies to the motor, with the addition that the motor can stop the window covering in ISY's console using Fade Stop (I have not found the api command that yields the right results though).

We can implement the binary switch type first to allow rudimentary on/off control of the window coverings.

Let me know and I can help provide any other info needed to implement this.

```
<node flag="128" nodeDefId="UZW003A">
    <address>ZW004_1</address>
    <name>Hallway Blinds Motor</name>
    <family>4</family>
    <parent type="3">1299</parent>
    <type>3.17.5.0</type>
    <enabled>true</enabled>
    <deviceClass>0</deviceClass>
    <wattage>0</wattage>
    <dcPeriod>0</dcPeriod>
    <startDelay>0</startDelay>
    <endDelay>0</endDelay>
    <pnode>ZW004_1</pnode>
    <sgid>1</sgid>
    <devtype>
        <gen>3.17.5</gen>
        <mfg>71.23122.21506</mfg>
        <cat>105</cat>
    </devtype>
    <ELK_ID>D09</ELK_ID>
    <property id="ST" value="100" formatted="100%" uom=""/>
</node>
<node flag="0" nodeDefId="UZW003B">
    <address>ZW004_147</address>
    <name>Hallway Blinds Switch</name>
    <family>4</family>
    <parent type="3">1299</parent>
    <type>3.17.5.0</type>
    <enabled>true</enabled>
    <deviceClass>0</deviceClass>
    <wattage>0</wattage>
    <dcPeriod>0</dcPeriod>
    <startDelay>0</startDelay>
    <endDelay>0</endDelay>
    <pnode>ZW004_1</pnode>
    <sgid>147</sgid>
    <devtype>
        <gen>3.17.5</gen>
        <mfg>71.23122.21506</mfg>
        <cat>147</cat>
    </devtype>
    <ELK_ID>D10</ELK_ID>
    <property id="ST" value="100" formatted="On" uom=""/>
</node>
```

**Comment by rodtoll** [comment]
@cptechie - Thank you for your interest in the library. At this time though I am unable to continue development of the plugin so this feature won't get added.
