### ISSUE TITLE
Expose scenes as devices. 

### ISSUE THREAD

**Issue by rodtoll** [rodtoll/isy-js#5]
Default to lighting devices? Or expose as a new object type?

Sounds like a good project for the upcoming holidays.

**Comment by respectTheCode** [comment]
I would suggest exposing Scenes as a new type since a Scene does not have a status.

**Comment by rodtoll** [comment]
Good point. I'll include a collection of the devices in the scene.

**Comment by rodtoll** [comment]
Implemented. Scenes are a different type and expose a collection of child devices. Basic lighting commands are available. Updated README.md to describe new class and functionality.

**Comment by rodtoll** [comment]
Pushed to package now.

**Comment by robwbartel** [comment]
Am I correct that this functionality is not (yet?) supported by the homebridge plugin?

**Comment by rodtoll** [comment]
Correct. Working on a test suite first so I can prevent regressions. Once that is in place will add scenes to the plugin. Should be this week.

**Comment by rodtoll** [comment]
@robwbartel This is now supported in the homebridge-isy-js plugin now. Enjoy.

**Comment by robwbartel** [comment]
Thanks for the heads up. Initial attempt inconclusive because I'm having trouble with HK database. Travel will prevent further testing for at least a couple of weeks.

**Comment by rodtoll** [comment]
No problem at all.
