### ISSUE TITLE
Adding z-wave device types

### ISSUE THREAD

**Issue by flintory5** [rodtoll/isy-js#6]
I have been able to add a few insteon device types, but for z-wave light switches, I'm not sure what the type would be. I see "4.64.3.0" for the Yale Door Lock z-wave device - where can I determine this for other z-wave devices?

**Comment by rodtoll** [comment]
Excellent question. I'm going to do some research with the ISY rest API and see how other zwave devices are exposed. 

You can try adding a device entry to devicetypes.json in the meantime. Go to http://<ISY ADDRESS>/rest/nodes in chrome and look at the resulting XML and look for your device. It will look like this:

```
<node flag="128">
<address>ZW002_1</address>
<name>Front Door Lock</name>
<family>4</family>
<parent type="3">9191</parent>
<type>4.64.3.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW002_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.64.3</gen>
<mfg>297.46443.65018</mfg>
<cat>111</cat>
<model>5</model>
</devtype>
<property id="ST" value="100" formatted="Locked" uom="11"/>
</node>
```

Look for the type node. That will be the device type.

**Comment by flintory5** [comment]
Thanks! That did the trick. I was able to add my GE Z-wave Jasco on/off switches successfully. Just had to get the device type right. 
{ "type": "4.16.1.0", "address": "", "name": "On/Off Power Switch", "deviceType": "Light", "connectionType": "ZWave", "batteryOperated": false }

**Comment by rodtoll** [comment]
Cool. I'll close this and starting an issue to add missing device types.
