### ISSUE TITLE
Missing device types

### ISSUE THREAD

**Issue by rodtoll** [rodtoll/isy-js#7]
Add devices you want to see added to this thread. If you post the json for the device (that should be added to devicetypes.json) I'll add it to a future revision of the package. 

To determine the device type go to http://<ISY ADDRESS>/rest/nodes in chrome and look at the resulting XML and look for your device. It will look like this:

```
<node flag="128">
<address>ZW002_1</address>
<name>Front Door Lock</name>
<family>4</family>
<parent type="3">9191</parent>
<type>4.64.3.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>ZW002_1</pnode>
<sgid>1</sgid>
<devtype>
<gen>4.64.3</gen>
<mfg>297.46443.65018</mfg>
<cat>111</cat>
<model>5</model>
</devtype>
<property id="ST" value="100" formatted="Locked" uom="11"/>
</node>
```

Look for the type node. That will be the device type. 

Or do a pull request with the change.

**Comment by rodtoll** [comment]
Example:

Please add they GE Z-wave Jasco on/off switches. 

Entry:
{ "type": "4.16.1.0", "address": "", "name": "On/Off Power Switch", "deviceType": "Light", "connectionType": "ZWave", "batteryOperated": false }

**Comment by robwbartel** [comment]
I fully understand I may be naive, but after a cursory reading of http://www.insteon.com/pdf/insteon_devcats_and_product_keys_20081008.pdf it seems to me there could be a default IsyDevice for at least device categories 01 and 02 (dimmable and switched devices respectively) that would eliminate a lot of missed device types for a lot of people. In my network of perhaps 20 devices only two were in the current isydevicelist.js.

**Comment by rodtoll** [comment]
Not naive at all and a good point. I'll add generic devices as you suggest using that doc. Good find.

In the meantime if you have specific device types you'd like to see added feel free to post them here or out in a pull request.

**Comment by PaulWieland** [comment]
This appears to be a new/missing type code for Insteon Motion Sensors:

  { "type": "16.1.65.0", "address": "1", "name": "(2842-222) Insteon Motion Sensor", "deviceType": "MotionSensor", "connectionType": "Insteon Wireless", "batteryOperated": true }

**Comment by rodtoll** [comment]
@fahrvergnuugen - added that new device type to the file. Not yet in package, will update npm package later today.

**Comment by rodtoll** [comment]
@robwbartel Opening new issue to track adding generic type support as you suggest.

**Comment by rodtoll** [comment]
All requested types were added. With new generic support dropping this issue. 

If someone detects a specific device class is not picked up then will open issues against the generic device identification code. Going to go away from the .json file mapping names.
