### ISSUE TITLE
Should respect <enabled> flag

### ISSUE THREAD

**Issue by robwbartel** [rodtoll/isy-js#9]
If a device is disabled in ISY it will still be shown in the accessories list recognized by isy-js. Should respect the "enabled" element.

**Comment by rodtoll** [comment]
True. Will fix.

**Comment by robwbartel** [comment]
Submitted PR 10 if you want it.

**Comment by rodtoll** [comment]
Fixed in the code. Disabled devices are now screened out. (Used your pull request contents, just not the pull request itself).

**Comment by rodtoll** [comment]
This is now in the published package.
